### ISSUE TITLE
EhCacheSecurityContextRepository

### ISSUE THREAD

**Issue by chasd00** [manish-in-java/spring-security-rest#1]
Shouldn't line 34 be

token = this.getToken(request)

?

Otherwise, aren't you returning the same token for every session via the hardcoded value in TokenGenerator and therefore overwriting every session in the cache with the newest one?

**Comment by manish-in-java** [comment]
`saveContext` is called after authentication succeeds for the first time.  It is never for an authenticated session afterwards.  In case of the implementation shown in this sample application, the authentication code would have been called only if the request did not contain the authentication header or the value passed in that header is not available in the in-memory cache.  Therefore, calling `getToken(request)` will return a `null` or a stale token.  The correct pattern for this part of the code is to extract the token from the `authentication` object generated by the authentication process, which is how it is right now.

You do have a valid concern about `TokenGenerator.generateToken` returning a hard-coded value.  This was provided just as an example.  Actual implementations should return a key that is strong enough to not be predictable or guessable.

**Comment by chasd00** [comment]
Got it, thanks.
